# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The audio stream url')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='True if the audio stream is working')),
            ],
        ),
        migrations.CreateModel(
            name='CameraParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.IntegerField(verbose_name='Center x')),
                ('center_y', models.IntegerField(verbose_name='Center y')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('video_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='parking.CameraInput', verbose_name='Camera input')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('camera_parking_spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot', to='parking.CameraParkingSpot', verbose_name='Camera parking spot')),
            ],
        ),
    ]
