# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraparkingspot',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='cameraparkingspot',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='cameraparkingspot',
            name='height',
        ),
        migrations.RemoveField(
            model_name='cameraparkingspot',
            name='width',
        ),
        migrations.AddField(
            model_name='cameraparkingspot',
            name='bottom_left_x',
            field=models.IntegerField(default=1, verbose_name='Bottom Left x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameraparkingspot',
            name='bottom_right_y',
            field=models.IntegerField(default=1, verbose_name='Bottom Right y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameraparkingspot',
            name='upper_right_x',
            field=models.IntegerField(default=1, verbose_name='Upper Right x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameraparkingspot',
            name='upper_right_y',
            field=models.IntegerField(default=1, verbose_name='Upper Right y'),
            preserve_default=False,
        ),
    ]
