# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
