# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
