# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerainput',
            name='url',
            field=models.CharField(help_text='The audio stream url', max_length=400),
        ),
    ]
