# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20180509_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameraparkingspot',
            old_name='video_input',
            new_name='camera',
        ),
    ]
