# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20180509_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraparkingspot',
            name='rotation_angle',
            field=models.IntegerField(default=0, verbose_name='Rotation Angle'),
        ),
    ]
