# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20180517_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerainput',
            name='url',
            field=models.TextField(help_text='The audio stream url'),
        ),
    ]
