# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20180517_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraparkingspot',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='camera_parking_spot',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='parking.CameraInput', verbose_name='Camera input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='center_x',
            field=models.IntegerField(default=1, verbose_name='Center x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='center_y',
            field=models.IntegerField(default=1, verbose_name='Center y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='rotation_angle',
            field=models.IntegerField(default=0, verbose_name='Rotation Angle'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Width'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CameraParkingSpot',
        ),
    ]
