# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20180518_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerainput',
            name='is_stream',
            field=models.BooleanField(default=True, help_text='True if the input is stream / False if the link is used for polling.'),
        ),
    ]
