# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_auto_20180519_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerainput',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='camerainput',
            name='is_stream',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='code',
            field=models.CharField(default=1, help_text='Identifier provided by the parking admin', max_length=300),
            preserve_default=False,
        ),
    ]
