# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_auto_20180626_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='bottom_right_y',
            new_name='bottom_left_y',
        ),
    ]
