# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_auto_20180626_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerainput',
            name='last_update',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
