# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_camerainput_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifier provided by the parking admin', max_length=300)),
                ('left_x', models.IntegerField(verbose_name='Median line x left')),
                ('left_y', models.IntegerField(verbose_name='Median line y left')),
                ('right_x', models.IntegerField(verbose_name='Median line x right')),
                ('right_y', models.IntegerField(verbose_name='Median line x right')),
                ('left_height', models.IntegerField(verbose_name='Height of left rectangle')),
                ('left_width', models.IntegerField(verbose_name='Width of left rectangle')),
                ('right_height', models.IntegerField(verbose_name='Height of right rectangle')),
                ('right_width', models.IntegerField(verbose_name='Width of right rectangle')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lanes', to='parking.CameraInput', verbose_name='Camera input'),
        ),
    ]
