# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_auto_20190204_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglane',
            name='left_height',
        ),
        migrations.RemoveField(
            model_name='parkinglane',
            name='left_x',
        ),
        migrations.RemoveField(
            model_name='parkinglane',
            name='left_y',
        ),
        migrations.RemoveField(
            model_name='parkinglane',
            name='right_height',
        ),
        migrations.RemoveField(
            model_name='parkinglane',
            name='right_x',
        ),
        migrations.RemoveField(
            model_name='parkinglane',
            name='right_y',
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='left_x_down',
            field=models.IntegerField(default=0, verbose_name='Median line x left DOWN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='left_x_up',
            field=models.IntegerField(default=0, verbose_name='Median line x left UP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='left_y_down',
            field=models.IntegerField(default=0, verbose_name='Median line y left DOWN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='left_y_up',
            field=models.IntegerField(default=0, verbose_name='Median line y left UP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='right_x_down',
            field=models.IntegerField(default=0, verbose_name='Median line x right DOWN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='right_x_up',
            field=models.IntegerField(default=0, verbose_name='Median line x right UP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='right_y_down',
            field=models.IntegerField(default=0, verbose_name='Median line y right DOWN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglane',
            name='right_y_up',
            field=models.IntegerField(default=0, verbose_name='Median line y right UP'),
            preserve_default=False,
        ),
    ]
